/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef NPU_RUNTIME_STATUS_H
#define NPU_RUNTIME_STATUS_H

enum npu_runtime_result {
  NPU_RUNTIME_SUCCESS = 0,
  NPU_RUNTIME_INVALID_ARGUMENT,
  NPU_RUNTIME_OUT_OF_RANGE,
  NPU_RUNTIME_FULL,
  NPU_RUNTIME_EMPTY,
  NPU_RUNTIME_OWNERSHIP_ERROR,
  NPU_RUNTIME_REJECTED,
  NPU_RUNTIME_TIMEOUT,
  NPU_RUNTIME_IO_ERROR,
};

#endif
